### ISSUE TITLE
How to use depth GT for training?

### ISSUE THREAD

**Issue by getterupper** [OpenDriveLab/LightwheelOcc#1]
Hi, thanks for your excellent job. I noticed that the depth GT provided in the dataset is not the actual depth of the scene but values between 0-254. Could you please share about how do you use the depth GT for training?

**Comment by sephyli** [comment]
Sorry for the inconvenience. We forget to include the information to docs.

Depth maps are stored as uint8 PNG images, where a value of 255 signifies an invalid pixel (i.e., out of range). For valid pixels, the depth in meters can be calculated by converting the uint8 value to a float and multiplying by $1000.0 / 255.0$:

$$
depth(u, v)=I(u, v) \times \frac{1000.0}{255.0}
$$

We have observed that the transformation process introduced some numerical errors. We plan to upload a version with improved accuracy shortly.

**Comment by ZM-Zhou** [comment]
Hello,
I have downloaded the depths from huggingface and I found that the depth maps have many stripes. it seems like they are out of the range of int8. How can I convert them to true depths?
![1710168978 394248](https://github.com/OpenDriveLab/LightwheelOcc/assets/55686739/1da52aff-f89e-40d4-ab0b-df530e0cc312)

**Comment by sephyli** [comment]
We have released a new version of depth image with more accurate precision. Please refer to [Getting Started](https://github.com/OpenDriveLab/LightwheelOcc/blob/main/docs/getting_started.md) to download the data. The usage of the data can be found in [toturial.ipynb](https://github.com/OpenDriveLab/LightwheelOcc/blob/main/docs/toturial.ipynb).
